// Generated by jextract

package com.mayreh.jktls.tls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tls12_crypto_info_aes_gcm_128 {
 *     struct tls_crypto_info info;
 *     unsigned char iv[8];
 *     unsigned char key[16];
 *     unsigned char salt[4];
 *     unsigned char rec_seq[8];
 * }
 * }
 */
public class tls12_crypto_info_aes_gcm_128 {

    tls12_crypto_info_aes_gcm_128() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tls_crypto_info.layout().withName("info"),
        MemoryLayout.sequenceLayout(8, tls_h.C_CHAR).withName("iv"),
        MemoryLayout.sequenceLayout(16, tls_h.C_CHAR).withName("key"),
        MemoryLayout.sequenceLayout(4, tls_h.C_CHAR).withName("salt"),
        MemoryLayout.sequenceLayout(8, tls_h.C_CHAR).withName("rec_seq")
    ).withName("tls12_crypto_info_aes_gcm_128");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout info$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("info"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct tls_crypto_info info
     * }
     */
    public static final GroupLayout info$layout() {
        return info$LAYOUT;
    }

    private static final long info$OFFSET = $LAYOUT.byteOffset(groupElement("info"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct tls_crypto_info info
     * }
     */
    public static final long info$offset() {
        return info$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct tls_crypto_info info
     * }
     */
    public static MemorySegment info(MemorySegment struct) {
        return struct.asSlice(info$OFFSET, info$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct tls_crypto_info info
     * }
     */
    public static void info(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, info$OFFSET, info$LAYOUT.byteSize());
    }

    private static final SequenceLayout iv$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("iv"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static final SequenceLayout iv$layout() {
        return iv$LAYOUT;
    }

    private static final long iv$OFFSET = $LAYOUT.byteOffset(groupElement("iv"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static final long iv$offset() {
        return iv$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static MemorySegment iv(MemorySegment struct) {
        return struct.asSlice(iv$OFFSET, iv$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static void iv(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, iv$OFFSET, iv$LAYOUT.byteSize());
    }

    private static long[] iv$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static long[] iv$dimensions() {
        return iv$DIMS;
    }
    private static final VarHandle iv$ELEM_HANDLE = iv$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static byte iv(MemorySegment struct, long index0) {
        return (byte)iv$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char iv[8]
     * }
     */
    public static void iv(MemorySegment struct, long index0, byte fieldValue) {
        iv$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout key$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("key"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static final SequenceLayout key$layout() {
        return key$LAYOUT;
    }

    private static final long key$OFFSET = $LAYOUT.byteOffset(groupElement("key"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static final long key$offset() {
        return key$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static MemorySegment key(MemorySegment struct) {
        return struct.asSlice(key$OFFSET, key$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static void key(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, key$OFFSET, key$LAYOUT.byteSize());
    }

    private static long[] key$DIMS = { 16 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static long[] key$dimensions() {
        return key$DIMS;
    }
    private static final VarHandle key$ELEM_HANDLE = key$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static byte key(MemorySegment struct, long index0) {
        return (byte)key$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char key[16]
     * }
     */
    public static void key(MemorySegment struct, long index0, byte fieldValue) {
        key$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout salt$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("salt"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static final SequenceLayout salt$layout() {
        return salt$LAYOUT;
    }

    private static final long salt$OFFSET = $LAYOUT.byteOffset(groupElement("salt"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static final long salt$offset() {
        return salt$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static MemorySegment salt(MemorySegment struct) {
        return struct.asSlice(salt$OFFSET, salt$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static void salt(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, salt$OFFSET, salt$LAYOUT.byteSize());
    }

    private static long[] salt$DIMS = { 4 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static long[] salt$dimensions() {
        return salt$DIMS;
    }
    private static final VarHandle salt$ELEM_HANDLE = salt$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static byte salt(MemorySegment struct, long index0) {
        return (byte)salt$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char salt[4]
     * }
     */
    public static void salt(MemorySegment struct, long index0, byte fieldValue) {
        salt$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final SequenceLayout rec_seq$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("rec_seq"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static final SequenceLayout rec_seq$layout() {
        return rec_seq$LAYOUT;
    }

    private static final long rec_seq$OFFSET = $LAYOUT.byteOffset(groupElement("rec_seq"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static final long rec_seq$offset() {
        return rec_seq$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static MemorySegment rec_seq(MemorySegment struct) {
        return struct.asSlice(rec_seq$OFFSET, rec_seq$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static void rec_seq(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rec_seq$OFFSET, rec_seq$LAYOUT.byteSize());
    }

    private static long[] rec_seq$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static long[] rec_seq$dimensions() {
        return rec_seq$DIMS;
    }
    private static final VarHandle rec_seq$ELEM_HANDLE = rec_seq$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static byte rec_seq(MemorySegment struct, long index0) {
        return (byte)rec_seq$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * unsigned char rec_seq[8]
     * }
     */
    public static void rec_seq(MemorySegment struct, long index0, byte fieldValue) {
        rec_seq$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

