// Generated by jextract

package com.mayreh.jktls.tls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct tls_crypto_info {
 *     uint16_t version;
 *     uint16_t cipher_type;
 * }
 * }
 */
public class tls_crypto_info {

    tls_crypto_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        tls_h.C_SHORT.withName("version"),
        tls_h.C_SHORT.withName("cipher_type")
    ).withName("tls_crypto_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfShort version$LAYOUT = (OfShort)$LAYOUT.select(groupElement("version"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t version
     * }
     */
    public static final OfShort version$layout() {
        return version$LAYOUT;
    }

    private static final long version$OFFSET = $LAYOUT.byteOffset(groupElement("version"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t version
     * }
     */
    public static final long version$offset() {
        return version$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t version
     * }
     */
    public static short version(MemorySegment struct) {
        return struct.get(version$LAYOUT, version$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t version
     * }
     */
    public static void version(MemorySegment struct, short fieldValue) {
        struct.set(version$LAYOUT, version$OFFSET, fieldValue);
    }

    private static final OfShort cipher_type$LAYOUT = (OfShort)$LAYOUT.select(groupElement("cipher_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t cipher_type
     * }
     */
    public static final OfShort cipher_type$layout() {
        return cipher_type$LAYOUT;
    }

    private static final long cipher_type$OFFSET = $LAYOUT.byteOffset(groupElement("cipher_type"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t cipher_type
     * }
     */
    public static final long cipher_type$offset() {
        return cipher_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t cipher_type
     * }
     */
    public static short cipher_type(MemorySegment struct) {
        return struct.get(cipher_type$LAYOUT, cipher_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t cipher_type
     * }
     */
    public static void cipher_type(MemorySegment struct, short fieldValue) {
        struct.set(cipher_type$LAYOUT, cipher_type$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

