// Generated by jextract

package com.mayreh.jktls.tls;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class tls_h extends tls_h$shared {

    tls_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    private static final int TLS_TX = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TLS_TX 1
     * }
     */
    public static int TLS_TX() {
        return TLS_TX;
    }
    private static final int TLS_RX = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TLS_RX 2
     * }
     */
    public static int TLS_RX() {
        return TLS_RX;
    }
    private static final int TLS_TX_ZEROCOPY_RO = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TLS_TX_ZEROCOPY_RO 3
     * }
     */
    public static int TLS_TX_ZEROCOPY_RO() {
        return TLS_TX_ZEROCOPY_RO;
    }
    private static final int TLS_RX_EXPECT_NO_PAD = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_RX_EXPECT_NO_PAD 4
     * }
     */
    public static int TLS_RX_EXPECT_NO_PAD() {
        return TLS_RX_EXPECT_NO_PAD;
    }
    private static final int TLS_1_2_VERSION_MAJOR = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TLS_1_2_VERSION_MAJOR 3
     * }
     */
    public static int TLS_1_2_VERSION_MAJOR() {
        return TLS_1_2_VERSION_MAJOR;
    }
    private static final int TLS_1_2_VERSION_MINOR = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TLS_1_2_VERSION_MINOR 3
     * }
     */
    public static int TLS_1_2_VERSION_MINOR() {
        return TLS_1_2_VERSION_MINOR;
    }
    private static final int TLS_1_3_VERSION_MAJOR = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TLS_1_3_VERSION_MAJOR 3
     * }
     */
    public static int TLS_1_3_VERSION_MAJOR() {
        return TLS_1_3_VERSION_MAJOR;
    }
    private static final int TLS_1_3_VERSION_MINOR = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_1_3_VERSION_MINOR 4
     * }
     */
    public static int TLS_1_3_VERSION_MINOR() {
        return TLS_1_3_VERSION_MINOR;
    }
    private static final int TLS_CIPHER_AES_GCM_128 = (int)51L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_128 51
     * }
     */
    public static int TLS_CIPHER_AES_GCM_128() {
        return TLS_CIPHER_AES_GCM_128;
    }
    private static final int TLS_CIPHER_AES_GCM_128_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_128_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_AES_GCM_128_IV_SIZE() {
        return TLS_CIPHER_AES_GCM_128_IV_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_128_KEY_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_128_KEY_SIZE 16
     * }
     */
    public static int TLS_CIPHER_AES_GCM_128_KEY_SIZE() {
        return TLS_CIPHER_AES_GCM_128_KEY_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_128_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_128_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_AES_GCM_128_SALT_SIZE() {
        return TLS_CIPHER_AES_GCM_128_SALT_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_128_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_128_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_AES_GCM_128_TAG_SIZE() {
        return TLS_CIPHER_AES_GCM_128_TAG_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_128_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_128_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_AES_GCM_128_REC_SEQ_SIZE() {
        return TLS_CIPHER_AES_GCM_128_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_256 = (int)52L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_256 52
     * }
     */
    public static int TLS_CIPHER_AES_GCM_256() {
        return TLS_CIPHER_AES_GCM_256;
    }
    private static final int TLS_CIPHER_AES_GCM_256_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_256_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_AES_GCM_256_IV_SIZE() {
        return TLS_CIPHER_AES_GCM_256_IV_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_256_KEY_SIZE = (int)32L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_256_KEY_SIZE 32
     * }
     */
    public static int TLS_CIPHER_AES_GCM_256_KEY_SIZE() {
        return TLS_CIPHER_AES_GCM_256_KEY_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_256_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_256_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_AES_GCM_256_SALT_SIZE() {
        return TLS_CIPHER_AES_GCM_256_SALT_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_256_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_256_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_AES_GCM_256_TAG_SIZE() {
        return TLS_CIPHER_AES_GCM_256_TAG_SIZE;
    }
    private static final int TLS_CIPHER_AES_GCM_256_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_GCM_256_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_AES_GCM_256_REC_SEQ_SIZE() {
        return TLS_CIPHER_AES_GCM_256_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_AES_CCM_128 = (int)53L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_CCM_128 53
     * }
     */
    public static int TLS_CIPHER_AES_CCM_128() {
        return TLS_CIPHER_AES_CCM_128;
    }
    private static final int TLS_CIPHER_AES_CCM_128_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_CCM_128_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_AES_CCM_128_IV_SIZE() {
        return TLS_CIPHER_AES_CCM_128_IV_SIZE;
    }
    private static final int TLS_CIPHER_AES_CCM_128_KEY_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_CCM_128_KEY_SIZE 16
     * }
     */
    public static int TLS_CIPHER_AES_CCM_128_KEY_SIZE() {
        return TLS_CIPHER_AES_CCM_128_KEY_SIZE;
    }
    private static final int TLS_CIPHER_AES_CCM_128_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_CCM_128_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_AES_CCM_128_SALT_SIZE() {
        return TLS_CIPHER_AES_CCM_128_SALT_SIZE;
    }
    private static final int TLS_CIPHER_AES_CCM_128_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_CCM_128_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_AES_CCM_128_TAG_SIZE() {
        return TLS_CIPHER_AES_CCM_128_TAG_SIZE;
    }
    private static final int TLS_CIPHER_AES_CCM_128_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_AES_CCM_128_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_AES_CCM_128_REC_SEQ_SIZE() {
        return TLS_CIPHER_AES_CCM_128_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_CHACHA20_POLY1305 = (int)54L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_CHACHA20_POLY1305 54
     * }
     */
    public static int TLS_CIPHER_CHACHA20_POLY1305() {
        return TLS_CIPHER_CHACHA20_POLY1305;
    }
    private static final int TLS_CIPHER_CHACHA20_POLY1305_IV_SIZE = (int)12L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_CHACHA20_POLY1305_IV_SIZE 12
     * }
     */
    public static int TLS_CIPHER_CHACHA20_POLY1305_IV_SIZE() {
        return TLS_CIPHER_CHACHA20_POLY1305_IV_SIZE;
    }
    private static final int TLS_CIPHER_CHACHA20_POLY1305_KEY_SIZE = (int)32L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_CHACHA20_POLY1305_KEY_SIZE 32
     * }
     */
    public static int TLS_CIPHER_CHACHA20_POLY1305_KEY_SIZE() {
        return TLS_CIPHER_CHACHA20_POLY1305_KEY_SIZE;
    }
    private static final int TLS_CIPHER_CHACHA20_POLY1305_SALT_SIZE = (int)0L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_CHACHA20_POLY1305_SALT_SIZE 0
     * }
     */
    public static int TLS_CIPHER_CHACHA20_POLY1305_SALT_SIZE() {
        return TLS_CIPHER_CHACHA20_POLY1305_SALT_SIZE;
    }
    private static final int TLS_CIPHER_CHACHA20_POLY1305_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_CHACHA20_POLY1305_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_CHACHA20_POLY1305_TAG_SIZE() {
        return TLS_CIPHER_CHACHA20_POLY1305_TAG_SIZE;
    }
    private static final int TLS_CIPHER_CHACHA20_POLY1305_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_CHACHA20_POLY1305_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_CHACHA20_POLY1305_REC_SEQ_SIZE() {
        return TLS_CIPHER_CHACHA20_POLY1305_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_SM4_GCM = (int)55L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_GCM 55
     * }
     */
    public static int TLS_CIPHER_SM4_GCM() {
        return TLS_CIPHER_SM4_GCM;
    }
    private static final int TLS_CIPHER_SM4_GCM_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_GCM_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_SM4_GCM_IV_SIZE() {
        return TLS_CIPHER_SM4_GCM_IV_SIZE;
    }
    private static final int TLS_CIPHER_SM4_GCM_KEY_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_GCM_KEY_SIZE 16
     * }
     */
    public static int TLS_CIPHER_SM4_GCM_KEY_SIZE() {
        return TLS_CIPHER_SM4_GCM_KEY_SIZE;
    }
    private static final int TLS_CIPHER_SM4_GCM_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_GCM_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_SM4_GCM_SALT_SIZE() {
        return TLS_CIPHER_SM4_GCM_SALT_SIZE;
    }
    private static final int TLS_CIPHER_SM4_GCM_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_GCM_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_SM4_GCM_TAG_SIZE() {
        return TLS_CIPHER_SM4_GCM_TAG_SIZE;
    }
    private static final int TLS_CIPHER_SM4_GCM_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_GCM_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_SM4_GCM_REC_SEQ_SIZE() {
        return TLS_CIPHER_SM4_GCM_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_SM4_CCM = (int)56L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_CCM 56
     * }
     */
    public static int TLS_CIPHER_SM4_CCM() {
        return TLS_CIPHER_SM4_CCM;
    }
    private static final int TLS_CIPHER_SM4_CCM_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_CCM_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_SM4_CCM_IV_SIZE() {
        return TLS_CIPHER_SM4_CCM_IV_SIZE;
    }
    private static final int TLS_CIPHER_SM4_CCM_KEY_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_CCM_KEY_SIZE 16
     * }
     */
    public static int TLS_CIPHER_SM4_CCM_KEY_SIZE() {
        return TLS_CIPHER_SM4_CCM_KEY_SIZE;
    }
    private static final int TLS_CIPHER_SM4_CCM_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_CCM_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_SM4_CCM_SALT_SIZE() {
        return TLS_CIPHER_SM4_CCM_SALT_SIZE;
    }
    private static final int TLS_CIPHER_SM4_CCM_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_CCM_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_SM4_CCM_TAG_SIZE() {
        return TLS_CIPHER_SM4_CCM_TAG_SIZE;
    }
    private static final int TLS_CIPHER_SM4_CCM_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_SM4_CCM_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_SM4_CCM_REC_SEQ_SIZE() {
        return TLS_CIPHER_SM4_CCM_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_128 = (int)57L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_128 57
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_128() {
        return TLS_CIPHER_ARIA_GCM_128;
    }
    private static final int TLS_CIPHER_ARIA_GCM_128_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_128_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_128_IV_SIZE() {
        return TLS_CIPHER_ARIA_GCM_128_IV_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_128_KEY_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_128_KEY_SIZE 16
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_128_KEY_SIZE() {
        return TLS_CIPHER_ARIA_GCM_128_KEY_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_128_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_128_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_128_SALT_SIZE() {
        return TLS_CIPHER_ARIA_GCM_128_SALT_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_128_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_128_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_128_TAG_SIZE() {
        return TLS_CIPHER_ARIA_GCM_128_TAG_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_128_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_128_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_128_REC_SEQ_SIZE() {
        return TLS_CIPHER_ARIA_GCM_128_REC_SEQ_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_256 = (int)58L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_256 58
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_256() {
        return TLS_CIPHER_ARIA_GCM_256;
    }
    private static final int TLS_CIPHER_ARIA_GCM_256_IV_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_256_IV_SIZE 8
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_256_IV_SIZE() {
        return TLS_CIPHER_ARIA_GCM_256_IV_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_256_KEY_SIZE = (int)32L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_256_KEY_SIZE 32
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_256_KEY_SIZE() {
        return TLS_CIPHER_ARIA_GCM_256_KEY_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_256_SALT_SIZE = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_256_SALT_SIZE 4
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_256_SALT_SIZE() {
        return TLS_CIPHER_ARIA_GCM_256_SALT_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_256_TAG_SIZE = (int)16L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_256_TAG_SIZE 16
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_256_TAG_SIZE() {
        return TLS_CIPHER_ARIA_GCM_256_TAG_SIZE;
    }
    private static final int TLS_CIPHER_ARIA_GCM_256_REC_SEQ_SIZE = (int)8L;
    /**
     * {@snippet lang=c :
     * #define TLS_CIPHER_ARIA_GCM_256_REC_SEQ_SIZE 8
     * }
     */
    public static int TLS_CIPHER_ARIA_GCM_256_REC_SEQ_SIZE() {
        return TLS_CIPHER_ARIA_GCM_256_REC_SEQ_SIZE;
    }
    private static final int TLS_SET_RECORD_TYPE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TLS_SET_RECORD_TYPE 1
     * }
     */
    public static int TLS_SET_RECORD_TYPE() {
        return TLS_SET_RECORD_TYPE;
    }
    private static final int TLS_GET_RECORD_TYPE = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TLS_GET_RECORD_TYPE 2
     * }
     */
    public static int TLS_GET_RECORD_TYPE() {
        return TLS_GET_RECORD_TYPE;
    }
    private static final int TLS_CONF_BASE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define TLS_CONF_BASE 1
     * }
     */
    public static int TLS_CONF_BASE() {
        return TLS_CONF_BASE;
    }
    private static final int TLS_CONF_SW = (int)2L;
    /**
     * {@snippet lang=c :
     * #define TLS_CONF_SW 2
     * }
     */
    public static int TLS_CONF_SW() {
        return TLS_CONF_SW;
    }
    private static final int TLS_CONF_HW = (int)3L;
    /**
     * {@snippet lang=c :
     * #define TLS_CONF_HW 3
     * }
     */
    public static int TLS_CONF_HW() {
        return TLS_CONF_HW;
    }
    private static final int TLS_CONF_HW_RECORD = (int)4L;
    /**
     * {@snippet lang=c :
     * #define TLS_CONF_HW_RECORD 4
     * }
     */
    public static int TLS_CONF_HW_RECORD() {
        return TLS_CONF_HW_RECORD;
    }
    private static final int TLS_INFO_UNSPEC = (int)0L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_UNSPEC = 0
     * }
     */
    public static int TLS_INFO_UNSPEC() {
        return TLS_INFO_UNSPEC;
    }
    private static final int TLS_INFO_VERSION = (int)1L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_VERSION = 1
     * }
     */
    public static int TLS_INFO_VERSION() {
        return TLS_INFO_VERSION;
    }
    private static final int TLS_INFO_CIPHER = (int)2L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_CIPHER = 2
     * }
     */
    public static int TLS_INFO_CIPHER() {
        return TLS_INFO_CIPHER;
    }
    private static final int TLS_INFO_TXCONF = (int)3L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_TXCONF = 3
     * }
     */
    public static int TLS_INFO_TXCONF() {
        return TLS_INFO_TXCONF;
    }
    private static final int TLS_INFO_RXCONF = (int)4L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_RXCONF = 4
     * }
     */
    public static int TLS_INFO_RXCONF() {
        return TLS_INFO_RXCONF;
    }
    private static final int TLS_INFO_ZC_RO_TX = (int)5L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_ZC_RO_TX = 5
     * }
     */
    public static int TLS_INFO_ZC_RO_TX() {
        return TLS_INFO_ZC_RO_TX;
    }
    private static final int TLS_INFO_RX_NO_PAD = (int)6L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.TLS_INFO_RX_NO_PAD = 6
     * }
     */
    public static int TLS_INFO_RX_NO_PAD() {
        return TLS_INFO_RX_NO_PAD;
    }
    private static final int __TLS_INFO_MAX = (int)7L;
    /**
     * {@snippet lang=c :
     * enum <anonymous>.__TLS_INFO_MAX = 7
     * }
     */
    public static int __TLS_INFO_MAX() {
        return __TLS_INFO_MAX;
    }
    private static final int TLS_1_2_VERSION = (int)771L;
    /**
     * {@snippet lang=c :
     * #define TLS_1_2_VERSION 771
     * }
     */
    public static int TLS_1_2_VERSION() {
        return TLS_1_2_VERSION;
    }
    private static final int TLS_1_3_VERSION = (int)772L;
    /**
     * {@snippet lang=c :
     * #define TLS_1_3_VERSION 772
     * }
     */
    public static int TLS_1_3_VERSION() {
        return TLS_1_3_VERSION;
    }
    private static final int TLS_INFO_MAX = (int)6L;
    /**
     * {@snippet lang=c :
     * #define TLS_INFO_MAX 6
     * }
     */
    public static int TLS_INFO_MAX() {
        return TLS_INFO_MAX;
    }
}

